parameters:
#    carp_mto.example.class: CARP\MtoBundle\Example

services:
#    carp_mto.example:
#        class: %carp_mto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
