<?php

namespace CARP\MtoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TareasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareasRepository extends EntityRepository
{
}
